version: "3.3"
networks:
  gitea:
    external: false
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ~/Desktop/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations

  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/Desktop/docker/snapdrop:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ~/Desktop/docker/influxdb2:/var/lib/influxdb2
  web:
    restart: always
    build: ~/Desktop/docker/Apache2/web
    volumes:
      - type: bind
        source: ~/Desktop/docker/Apache2/web
        target: /web
      - type: bind
        source: ~/Desktop/docker/Apache2/files
        target: /var/www/html
    ports:
      - 65534:80
    container_name: web

  server:
    image: gitea/gitea:1.21.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      # ip address of mysql docker
      - GITEA__database__HOST=172.20.0.2:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ~/Desktop/docker/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - gitea_db

  gitea_db:
    image: mysql:8
    restart: always
    container_name: gitea_db
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ~/Desktop/docker/gitea/mysql:/var/lib/mysql
